project:
  type: website

website:
  title: "Atlas"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - icon: github
        href: https://github.com/etranos/atlas
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

